- name: Ajout de dotDeb aux depots
  apt_repository: repo='{{ item }}'
  with_items:
    - deb http://packages.dotdeb.org jessie all
    - deb-src http://packages.dotdeb.org jessie all

- name: Ajout de la cle dotdeb
  apt_key: 
    url: https://www.dotdeb.org/dotdeb.gpg
    state: present

- name: APT update
  apt: update_cache=yes

- name: Installation de php
  apt: name={{ item }} state=latest
  with_items: php7.0